services:
  web:
    build: .
  proxy:
    image: nginx
    volumes:
      - type: bind
        source: /etc/nginx/
        target: /etc/nginx/
        read_only: true
      - type: bind
        source: /etc/letsencrypt
        target: /etc/letsencrypt
        read_only: true
    ports:
      - 443:443
    depends_on:
      - web
