services:
  web:
    build: .
    ports:
      - "3000:3000"
  proxy:
    image: nginx
    volumes:
      - type: bind
        source: /etc/nginx/nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
      - type: bind
        source: /etc/letsencrypt
        target: /etc/letsencrypt
        read_only: true
    ports:
      - 80:80
    depends_on:
      - web
